/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as ReservationIdRouteImport } from './routes/reservation.$id'
import { Route as PaystackIdRouteImport } from './routes/paystack.$id'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoomsRoute,
} as any)
const ReservationIdRoute = ReservationIdRouteImport.update({
  id: '/reservation/$id',
  path: '/reservation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaystackIdRoute = PaystackIdRouteImport.update({
  id: '/paystack/$id',
  path: '/paystack/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/paystack/$id': typeof PaystackIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/paystack/$id': typeof PaystackIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/paystack/$id': typeof PaystackIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/dashboard'
    | '/vault'
    | '/paystack/$id'
    | '/reservation/$id'
    | '/rooms/$slug'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/dashboard'
    | '/vault'
    | '/paystack/$id'
    | '/reservation/$id'
    | '/rooms/$slug'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/rooms'
    | '/_authenticated/dashboard'
    | '/_authenticated/vault'
    | '/paystack/$id'
    | '/reservation/$id'
    | '/rooms/$slug'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  PaystackIdRoute: typeof PaystackIdRoute
  ReservationIdRoute: typeof ReservationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/reservation/$id': {
      id: '/reservation/$id'
      path: '/reservation/$id'
      fullPath: '/reservation/$id'
      preLoaderRoute: typeof ReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paystack/$id': {
      id: '/paystack/$id'
      path: '/paystack/$id'
      fullPath: '/paystack/$id'
      preLoaderRoute: typeof PaystackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RoomsRouteChildren {
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  RoomsRoute: RoomsRouteWithChildren,
  PaystackIdRoute: PaystackIdRoute,
  ReservationIdRoute: ReservationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
